package com.demo.entity;

public class Boy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boy.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boy.height
     *
     * @mbg.generated
     */
    private String height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boy.id
     *
     * @return the value of boy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boy.id
     *
     * @param id the value for boy.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boy.name
     *
     * @return the value of boy.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boy.name
     *
     * @param name the value for boy.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boy.height
     *
     * @return the value of boy.height
     *
     * @mbg.generated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boy.height
     *
     * @param height the value for boy.height
     *
     * @mbg.generated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }
}