package com.demo.dao;

import com.demo.entity.Boy;

public interface BoyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boy
     *
     * @mbg.generated
     */
    int insert(Boy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boy
     *
     * @mbg.generated
     */
    int insertSelective(Boy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boy
     *
     * @mbg.generated
     */
    Boy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Boy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Boy record);
}